apiVersion: apps/v1
kind: Deployment
metadata:
  name: raster-dtfr-deployment
  labels:
    app: raster-dtfr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raster-dtfr
  template:
    metadata:
      labels:
        app: raster-dtfr
    spec:
      containers:
      - name: raster-dtfr
        image: dtfr-api-img
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: raster-dtfr-service
spec:
  type: NodePort
  selector:
    app: raster-dtfr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30200
